// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function ResolveFont(arg1) {
  return window['go']['app']['App']['ResolveFont'](arg1);
}

export function SetConfig(arg1) {
  return window['go']['app']['App']['SetConfig'](arg1);
}

export function SetWindowBackground(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetWindowBackground'](arg1, arg2, arg3);
}

export function SetWindowTitle(arg1) {
  return window['go']['app']['App']['SetWindowTitle'](arg1);
}
